ENTERPRISE_LOGO_URL: /static/img/quay-horizontal-color.svg
FEATURE_SUPER_USERS: true
SUPER_USERS:
- admin
PREFERRED_URL_SCHEME: https
REGISTRY_TITLE: Quay
REGISTRY_TITLE_SHORT: Quay
SERVER_HOSTNAME: registry.skynet-dev.com
