ENTERPRISE_LOGO_URL: /static/img/quay-horizontal-color.svg
FEATURE_MAILING: false
FEATURE_SUPER_USERS: true
SUPER_USERS:
- admin
PREFERRED_URL_SCHEME: http
REGISTRY_TITLE: Quay
REGISTRY_TITLE_SHORT: Quay
SERVER_HOSTNAME: quay-test.tiki-dsp.tech
DISTRIBUTED_STORAGE_CONFIG:
    default:
    - RadosGWStorage
    - access_key: <REDACTED>
      secret_key: <REDACTED>
      hostname: s3.tiki-dsp.tech
      bucket_name: quay-test
      port: 443
      is_secure: true
      storage_path: /quay-datastorage/registry
DISTRIBUTED_STORAGE_DEFAULT_LOCATIONS: []
DISTRIBUTED_STORAGE_PREFERENCE:
    - default