apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: quay-postgres
  labels:
    quay-component: postgres
spec:
  storageClassName: ceph-fs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ceph-fs
