# Clair overlay adds Clair v4 security scanner and its database.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: 
  - ../../base
  - ./clair.deployment.yaml
  - ./clair.service.yaml
  - ./postgres.deployment.yaml
  - ./postgres.service.yaml
secretGenerator:
  - name: clair-config-secret
    files:
      - config.yaml=./clair-config.yaml
  # Add Clair fields to `config.yaml` (https://github.com/kubernetes-sigs/kustomize/blob/master/examples/combineConfigs.md)
  - name: quay-config-secret
    behavior: merge
    literals:
      - FEATURE_SECURITY_SCANNER=true
      - SECURITY_SCANNER_V4_ENDPOINT=http://clair
      - SECURITY_SCANNER_V4_NAMESPACE_WHITELIST=[alecmerdler, devtable]
