apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
components:
  - ../components/postgres
  - ../components/redis
  - ../components/clair
  # - ../components/storage
secretGenerator:
  - name: quay-config-secret
    behavior: merge
    files:
      - ./bundle/config.yaml
      # - ./bundle/ssl.cert
      # - ./bundle/ssl.key
