http_listen_addr: ":8080"
introspection_addr: ":8089"
log_level: "info"
indexer:
  connstring: "host=clair-postgres port=5432 dbname=clair user=postgres password=postgres sslmode=disable"
  scanlock_retry: 10
  layer_scan_concurrency: 5
  migrations: true
matcher:
  connstring: "host=clair-postgres port=5432 dbname=clair user=postgres password=postgres sslmode=disable"
  indexer_addr: "clair-indexer"
  migrations: true
notifier:
  indexer_addr: "http://clair-indexer:8080/"
  matcher_addr: "http://clair-matcher:8080/"
  connstring: "host=clair-postgres port=5432 dbname=clair user=postgres password=postgres sslmode=disable"
  migrations: true
  delivery_interval: 1m
  poll_interval: 5m
metrics:
  name: "prometheus"
  prometheus:
      endpoint: monitoring-prometheus-service.infrastructure.svc.cluster.local:8080