apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: quay-datastore
  labels:
    quay-component: quay-app
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: quay-datastore
        quay-component: quay-app
    spec:
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: minio-pv-claim
      containers:
      # TODO(alecmerdler): Sidecar container which creates `quay-datastore` bucket (https://github.com/minio/minio/issues/4882)
      - name: minio
        image: minio/minio
        command: ["minio"]
        args: ["server", "/storage"]
        env:
        # FIXME(alecmerdler): Put these in a `Secret` and reference using `valueFrom.secretKeyRef`...
        - name: MINIO_ACCESS_KEY
          value: "minio"
        - name: MINIO_SECRET_KEY
          value: "minio123"
        ports:
        - containerPort: 9000
        volumeMounts:
        - name: storage 
          mountPath: "/storage"
