# TODO(alecmerdler): Remove this and/or add to `dev` overlay
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: quay-datastorage
  labels:
    quay-component: quay-app
spec:
  storageClassName: ceph-fs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
