apiVersion: apps/v1
kind: Deployment
metadata:
  name: quay-app
  labels:
    quay-component: quay-app
spec:
  replicas: 1
  selector:
    matchLabels:
      quay-component: quay-app
  template:
    metadata:
      labels:
        quay-component: quay-app
    spec:
      securityContext:
        fsGroup: 1001
      volumes:
        - name: configvolume
          secret:
            secretName: quay-config-secret
        # TODO(alecmerdler): Maybe we have this as a "dev" overlay...?
        - name: quay-datastorage
          persistentVolumeClaim:
            claimName: quay-datastorage
      containers:
        - name: quay-app
          # NOTE: Using image that can start with empty database
          image: quay.io/alecmerdler/quay@sha256:5f7981fa27af440aa9b293a0fa35fd88ee8f9df18a7bff4403a49ae135339df1
          env:
            - name: QE_K8S_CONFIG_SECRET
              # FIXME(alecmerdler): Using `vars` is kinda ugly because it's basically templating, but this needs to be the generated `Secret` name...
              value: $(QE_K8S_CONFIG_SECRET)
            - name: QE_K8S_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: DEBUGLOG
              value: "true"
          ports:
            - containerPort: 8443
            - containerPort: 8081
          volumeMounts:
            - name: configvolume
              readOnly: false
              mountPath: /conf/stack
            - name: quay-datastorage
              mountPath: /datastorage
