# Postgres overlay adds a Postgres database for Quay to use
apiVersion: kustomize.config.k8s.io/v1beta1
kind: KustomizationPatch
resources: 
  # TODO(alecmerdler): Use `components` when supported (https://github.com/kubernetes-sigs/kustomize/issues/1251)
  # - ../../base
  - ./postgres.deployment.yaml
  - ./postgres.service.yaml
generatorOptions:
  disableNameSuffixHash: true
secretGenerator:
  # Add Postgres fields to `config.yaml` (https://github.com/kubernetes-sigs/kustomize/blob/master/examples/combineConfigs.md)
  - name: quay-config-secret-postgres
    behavior: merge
    files:
      - DATABASE_SECRET_KEY=./database-secret-key.yaml
      - DB_URI=./db-uri.yaml
